-- Supabase schema for Neon Party landing page

-- Enable UUID generation
create extension if not exists pgcrypto;

-- Enum for moderation status
do $$
begin
  if not exists (select 1 from pg_type where typname = 'photo_status') then
    create type public.photo_status as enum ('pending', 'approved', 'rejected');
  end if;
end $$;

-- Photos uploaded by guests (moderated gallery)
create table if not exists public.photos (
  id uuid primary key default gen_random_uuid(),
  guest_name text not null,
  image_url text not null,
  public_id text,
  status public.photo_status not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists photos_created_at_idx on public.photos (created_at desc);
create index if not exists photos_status_idx on public.photos (status);

-- Global settings for the gallery
create table if not exists public.gallery_settings (
  id bigint generated by default as identity primary key,
  uploads_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

-- Keep updated_at fresh
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists gallery_settings_set_updated_at on public.gallery_settings;
create trigger gallery_settings_set_updated_at
before update on public.gallery_settings
for each row
execute function public.set_updated_at();

-- Seed a default row (id will be 1 on empty db)
insert into public.gallery_settings (uploads_enabled)
select true
where not exists (select 1 from public.gallery_settings);

-- Notes:
-- - RLS policies are intentionally not enabled yet; you can add them when defining
--   auth/admin strategy.
